PROJECT="testkeycloak"
LXD_IMAGE=ubuntu:24.04
LXD_POOL=default
IPADDR_PREFIX=10.60.204
IPADDR_PREFIX1=10.60.205

LXC=lxc

HOST1="${PROJECT}-kc1"
HOST_MANAGE="${PROJECT}-manage"
DB_HOSTS="kc1 kc2 kc3"
HOSTS="${DB_HOSTS} manage"
NETWORK0_NAME=${PROJECT}0
NETWORK1_NAME=${PROJECT}1
PROFILE_NAME=${PROJECT}-prof
VIP="${IPADDR_PREFIX}.11"
