PROJECT="testkeycloak"
LXD_IMAGE=ubuntu:24.04
IPADDR_PREFIX=10.60.204

HOST1="${PROJECT}-kc1"
HOST_MANAGE="${PROJECT}-manage"
DB_HOSTS="kc1 kc2 kc3"
HOSTS="${DB_HOSTS} manage"
NETWORK_NAME=$PROJECT
PROFILE_NAME=${PROJECT}-prof
VIP="${IPADDR_PREFIX}.11"

LXC=lxc
